version: "3"

services:
  db:
    image: example/db:1.0.0
    build:
      context: ./db
    env_file:
      - ./.env
    ports:
      - 5432:5432
    command: postgres
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c shared_preload_libraries=wal2json

  graphql:
    image: example/graphql:1.0.0
    build:
      context: ./graphql
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - 5433:5433
    command: [
        "--plugins",
        "@graphile/pg-pubsub",
        "--connection",
        "${DATABASE_URL}",
        "--port",
        "5433",
        "--schema",
        "public",
        "--live",
        "--subscriptions",
        "--enhance-graphiql",
        "--cors",
        "--append-plugins",
        "postgraphile-plugin-connection-filter,\
        @graphile-contrib/pg-simplify-inflector,\
        @graphile-contrib/pg-order-by-related,\
        @graphile/subscriptions-lds",
      ]
